name: Code Quality

on:
  push:
    branches:
      - develop
  pull_request:

jobs:
  code-quality:
    uses: alleyinteractive/.github/.github/workflows/php-composer-command.yml@main
    with:
      php: 8.1
      command: |
        phpcs
        phpstan
